version: '3.8'

services:
  app:
    build: .
    ports:
      - '4444:4444'
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
