FROM node:lts-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

EXPOSE 4444

COPY wait-for-it.sh .
RUN chmod +x wait-for-it.sh

CMD ["sh", "-c", "./wait-for-it.sh postgres:5432 -- npx drizzle-kit migrate && node dist/src/main"]
